from __future__ import annotations

from typing import Protocol


class WeChatDriver(Protocol):
    name: str

    def is_running(self) -> bool: ...

    def is_logged_in(self) -> bool: ...

    def activate(self) -> None: ...

    def search_chat(self, keyword: str) -> bool: ...

    def open_chat(self, name: str) -> None: ...

    def send_text(self, text: str) -> None: ...

    def send_file(self, file_path: str) -> None: ...

    def read_current_chat_messages(self) -> dict[str, object]: ...

    def read_visible_chat_snapshots(self, unread_only: bool = False) -> dict[str, object]: ...

    def capture_state(self) -> dict[str, str]: ...
